export const companiesList = [
    {name:"Apple",symbol:"AAPL"},
    {name:"3m",symbol:"MMM"},
    {name:"Abbott Laboratories",symbol:"ABT"},
    {name:"Abbvie",symbol:"ABBV"},
    {name:"Accenture",symbol:"ACN"},
    {name:"Adobe",symbol:"ADBE"},
    {name:"Allstate",symbol:"ALL"},
    {name:"Alphabet",symbol:"GOOGL"},
    {name:"Altria Group",symbol:"MO"},
    {name:"Amazon Com",symbol:"AMZN"},
    {name:"American Express",symbol:"AXP"},
    {name:"American International Group",symbol:"AIG"},
    {name:"American Tower",symbol:"AMT"},
    {name:"Amgen",symbol:"AMGN"},
    {name:"AT&T",symbol:"T"},
    {name:"Bank Of America",symbol:"BAC"},
    {name:"Bank Of New York Mellon",symbol:"BK"},
    {name:"Berkshire Hathaway",symbol:"BRKB"},
    {name:"Biogen",symbol:"BIIB"},
    {name:"Blackrock",symbol:"BLK"},
    {name:"Blk Csh Fnd Treasury Sl Agency",symbol:"XTSLA"},
    {name:"Boeing",symbol:"BA"},
    {name:"Booking Holdings",symbol:"BKNG"},
    {name:"Bristol Myers Squibb",symbol:"BMY"},
    {name:"Capital One Financial",symbol:"COF"},
    {name:"Caterpillar",symbol:"CAT"},
    {name:"Charter Communications",symbol:"CHTR"},
    {name:"Chevron",symbol:"CVX"},
    {name:"Cisco Systems",symbol:"CSCO"},
    {name:"Citigroup",symbol:"C"},
    {name:"Coca-cola",symbol:"KO"},
    {name:"Colgate-Palmolive",symbol:"CL"},
    {name:"Comcast",symbol:"CMCSA"},
    {name:"Conocophillips",symbol:"COP"},
    {name:"Costco Wholesale",symbol:"COST"},
    {name:"CVS Health",symbol:"CVS"},
    {name:"Danaher",symbol:"DHR"},
    {name:"Dow",symbol:"DOW"},
    {name:"Duke Energy",symbol:"DUK"},
    {name:"Dupont De Nemours",symbol:"DD"},
    {name:"Eli Lilly",symbol:"LLY"},
    {name:"Emerson Electric",symbol:"EMR"},
    {name:"Exelon",symbol:"EXC"},
    {name:"Exxon Mobil",symbol:"XOM"},
    {name:"Facebook",symbol:"FB"},
    {name:"Fedex",symbol:"FDX"},
    {name:"Ford Motor",symbol:"F"},
    {name:"General Dynamics",symbol:"GD"},
    {name:"General Electric",symbol:"GE"},
    {name:"General Motors",symbol:"GM"},
    {name:"Gilead Sciences",symbol:"GILD"},
    {name:"Goldman Sachs Group",symbol:"GS"},
    {name:"Home Depot",symbol:"HD"},
    {name:"Honeywell International",symbol:"HON"},
    {name:"Inteloration",symbol:"INTC"},
    {name:"International Business Machines",symbol:"IBM"},
    {name:"Johnson & Johnson",symbol:"JNJ"},
    {name:"Jpmorgan Chase",symbol:"JPM"},
    {name:"Kinder Morgan",symbol:"KMI"},
    {name:"Kraft Heinz",symbol:"KHC"},
    {name:"Lockheed Martin",symbol:"LMT"},
    {name:"Lowes Companies",symbol:"LOW"},
    {name:"Mastercard",symbol:"MA"},
    {name:"Mcdonalds",symbol:"MCD"},
    {name:"Medtronic",symbol:"MDT"},
    {name:"Merck",symbol:"MRK"},
    {name:"Metlife",symbol:"MET"},
    {name:"Microsoft",symbol:"MSFT"},
    {name:"Mondelez International",symbol:"MDLZ"},
    {name:"Morgan Stanley",symbol:"MS"},
    {name:"Netflix",symbol:"NFLX"},
    {name:"Nextera Energy",symbol:"NEE"},
    {name:"Nike",symbol:"NKE"},
    {name:"Nvidia",symbol:"NVDA"},
    {name:"Oracle",symbol:"ORCL"},
    {name:"Paypal Holdings",symbol:"PYPL"},
    {name:"Pepsico",symbol:"PEP"},
    {name:"Pfizer",symbol:"PFE"},
    {name:"Philip Morris International",symbol:"PM"},
    {name:"Procter & Gamble",symbol:"PG"},
    {name:"Qualcomm",symbol:"QCOM"},
    {name:"Raytheon Technologies",symbol:"RTX"},
    {name:"Salesforce",symbol:"CRM"},
    {name:"Schlumberger",symbol:"SLB"},
    {name:"Simon Property Group",symbol:"SPG"},
    {name:"Southern",symbol:"SO"},
    {name:"Starbucks",symbol:"SBUX"},
    {name:"Target",symbol:"TGT"},
    {name:"Tesla",symbol:"TSLA"},
    {name:"Texas Instrument",symbol:"TXN"},
    {name:"Thermo Fisher Scientific",symbol:"TMO"},
    {name:"Union Pacific",symbol:"UNP"},
    {name:"United Parcel Service",symbol:"UPS"},
    {name:"Unitedhealth Group",symbol:"UNH"},
    {name:"US Bancorp",symbol:"USB"},
    {name:"Verizon Communications",symbol:"VZ"},
    {name:"Visa",symbol:"V"},
    {name:"Walgreen Boots Alliance",symbol:"WBA"},
    {name:"Walmart",symbol:"WMT"},
    {name:"Walt Disney",symbol:"DIS"},
    {name:"Wells Fargo",symbol:"WFC"}
] 